{
  SAXParseException exception=new SAXParseException("Oops!",null);
  try {
    parent.fatalError(exception);
  }
 catch (  SAXException e) {
    throw new RuntimeException("Unexpected exception",e);
  }
  assertEquals(logger.size(),1);
  assertEquals("fatalError",logger.getMethod());
  assertEquals(new Object[]{exception},logger.getArgs());
}
