{
  int[] x={0};
  boolean thrown=false;
  try {
    Array.set(x,0,new Integer(1));
  }
 catch (  Exception e) {
    fail("Exception during get test : " + e.getMessage());
  }
  assertEquals("Get returned incorrect value",1,((Integer)Array.get(x,0)).intValue());
  try {
    Array.set(new Object(),0,new Object());
  }
 catch (  IllegalArgumentException e) {
    thrown=true;
  }
  if (!thrown) {
    fail("Passing non-array failed to throw exception");
  }
  thrown=false;
  try {
    Array.set(x,4,new Integer(1));
  }
 catch (  ArrayIndexOutOfBoundsException e) {
    thrown=true;
  }
  if (!thrown) {
    fail("Invalid index failed to throw exception");
  }
  boolean exception=false;
  try {
    Array.set(new int[1],0,null);
  }
 catch (  IllegalArgumentException e) {
    exception=true;
  }
  assertTrue("expected exception not thrown",exception);
  thrown=false;
  try {
    Array.set(null,0,2);
  }
 catch (  NullPointerException e) {
    thrown=true;
  }
  if (!thrown) {
    fail("Null argument failed to throw NPE");
  }
}
