{
  simple1.throwExceptionOnNextUse=true;
  try {
    si.close();
    fail("IOException not thrown!");
  }
 catch (  IOException e) {
  }
}
