{
  UndeclaredThrowableException ute=new UndeclaredThrowableException(throwable);
  assertSame("Wrong cause returned",throwable,ute.getCause());
}
