{
  try {
    PublicAccess.main();
    System.err.println("ERROR: call 1 not expected to succeed");
  }
 catch (  VerifyError ve) {
    System.out.println("Got expected failure 1");
  }
catch (  IllegalAccessError iae) {
    System.out.println("Got expected failure 1");
  }
  try {
    CheckInstanceof.main(new Object());
    System.err.println("ERROR: call 2 not expected to succeed");
  }
 catch (  VerifyError ve) {
    System.out.println("Got expected failure 2");
  }
catch (  IllegalAccessError iae) {
    System.out.println("Got expected failure 2");
  }
}
